### PR TITLE
debian: rename vitamtp{4,-dev} packages to libvitamtp*

### PR DESCRIPTION
**Pull request by a-detiste**
In most case, a library package name should match it's soname.
The binary package name doesn't need to be identical to the source package name

Example: `mesa` gives `libgl*`
https://packages.qa.debian.org/m/mesa.html

I've tested this upgrade on my own repository I built with `reprepro` and installation went fine
https://gist.github.com/a-detiste/67815ac02a71d45afa1e
http://ssh.detiste.be/

### CODE REVIEW

**Comment by codestation** [comment]
Seems like a good change but i still have to test how a name change wll affect the upgrade from previous users since the old package and the new one with have a conflict on all the installed files.

**Comment by a-detiste** [comment]
> conflict on all the installed files
apt-get or aptitude would handle that automaticaly;
```
Conflicts: vitamtp4
Replaces: vitamtp4
```
If a user install from time to time with manual download + `dpkg -i`;
dpkg is more low level and will complain.

**Comment by codestation** [comment]
Gonna go with case [nº5](https://wiki.debian.org/PackageTransition) for the transition, so i will be creating a transitional package for those who are upgrading from the old version in the ubuntu ppa.

**Comment by a-detiste** [comment]
Thanks, :+1:  that's great.  

The transitional package is only usefull to co-oridinate complex transitions that impacats many packages (like `libjpeg`) or if there are other package outside of your ppa that depends on vitamtp4; that I can't know (original openCMA ?) & in anyway this extraneous package wouldn't hurt.

https://wiki.debian.org/Renaming_a_Package
Here simplest method 1 will work: new `qcma` package will pull up `libvitamtp4` automatically & that will remove automatically installed `vitamtp4` (the `Provides:` is not necessary, as the new `qcma`has the right `Depends:`)

**Pull request merged**
